baseURL: 'https://startwords.cdh.princeton.edu/'
title: DHQwords
theme: startwords
copyright: >-
  This work is licensed under a Creative Commons Attribution-NoDerivatives 4.0 International License.
enableEmoji: true
# googleAnalytics:
enableRobotsTXT: true
enableGitInfo: true
timeout: 300s
taxonomies:
  category: categories
  tag: tags
disableKinds:
  # - taxonomy
  # - term
  # - tag
permalinks:
  issues: '/:sections/:slug/'

outputFormats:
  TXT:
    mediaType: text/plain
outputs:
  home:
    - HTML
    - RSS
    - ATOM
  section:
    - HTML
    - RSS
    - ATOM
  page:
    - HTML
    # - TXT  # disable plaintext article version created in SW

menu:
  footer:
    - name: About
      url: about/
      weight: 20
    - name: Keywords
      url: categories/
      weight: 30
    - name: Tags
      url: tags/
      weight: 3
    # - name: Authors
    #   url: authors/
    #   weight: 30


Author:
  name:
  email: cdh-info@princeton.edu

params:
  shortTitle: dhq
  dateform: 'January 2, 2006'
  dateformShort: January 2
  dateformNum: '2006-01-02'
  dateformNumTime: '2006-01-02 15:04 -0700'
  license: 'http://creativecommons.org/licenses/by/4.0/'
  license_text: Creative Commons Attribution No-Derivatives 4.0 International License
  images:
    - social.png
  description: >-
     an experiment republishing DHQ articles with Hugo & Startwords theme.
  absoluteArticleLinks: false
  # logo
  # logotype
  num_features: 0

defaultContentLang: en

languages:
  en:
    languageName: English
    weight: 1
    params:
      available_in: Available in English
  es:
    languageName: Español
    weight: 2
    params:
      license_text: Atribución-SinDerivadas 4.0 Internacional. (CC BY ND 4.0)
      description: "Un experimento republicando artículos de DHQ con el tema Hugo & Startwords."
      available_in: Disponible en Español
    menu:
      footer:
        # - name: Acerca de
        #   url: /es/acerca-de/
        #   weight: 20
        - name: Keywords
          url: categories/
        - name: Tags
          url: tags/
          weight: 3

  #       - name: Authors
  #         url: authors/
  #         weight: 30
  fr:
    languageName: français
    weight: 3
    params:
      license_text: Pas de Modification 4.0 International. (CC BY ND 4.0)
      description: "Une expérience de republication d'articles de DHQ avec le thème Hugo & Startwords."
      available_in: Disponible en français
  pt:
    languageName: Portuguese
    weight: 4
    params:
      available_in: Disponível em português
      description: "Um experimento republicando artigos do DHQ com o tema Hugo & Startwords"
      license_text: Atribuição-SemDerivações 4.0 Internacional. (CC BY ND 4.0)
  # de:
  #   languageName: Deutsch
  #   weight: 5
  #   params:
  #     license_text: Pas de Modification 4.0 International. (CC BY ND 4.0)
  #     description: ""
  #     available_in: Disponible en Español
  # there is one german langUsage tag but no german content


markup:
  goldmark:
    renderer:
      unsafe: true
      hardWraps: true

security:
  enableInlineShortcodes: false
  exec:
    allow:
      - ^dart-sass-embedded$
      - ^go$
      - ^npx$
      - ^postcss$
      - ^babel$
    osEnv:
      - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$
  funcs:
    getenv:
      - ^HUGO_
  http:
    methods:
      - (?i)GET|POST
    urls:
      - .*
